In [1]:
a = [
    [4,8,2],
    [9,5,1]
    ]
print(a)

[[4, 8, 2], [9, 5, 1]]


In [3]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [4]:
array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
array1=np.ones((8,4))
print(array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
num1 = 25
num2 = 5 
sum = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2
print(f"toplam={sum} , fark={sub}, çarpım={mul}, bölüm={div}")

toplam=30 , fark=20, çarpım=125, bölüm=5.0


In [12]:
x=10
print(x)
x+=5
print(x)
x-=2
print(x)

10
15
13


In [15]:
number = int(input("Enter a number: "))
if number>0:
    print("Number is POSITIVE! ")
elif number<0:
    print("Number is NEGATIVE! ")
else:
    print("Number is ZERO !")

Enter a number: 0
Number is ZERO !


In [21]:
for i in range(10):
    print(f"--> {i}")


--> 0
--> 1
--> 2
--> 3
--> 4
--> 5
--> 6
--> 7
--> 8
--> 9


In [24]:
for j in range(15,10,-1):
    print(f"--> {j}")

--> 15
--> 14
--> 13
--> 12
--> 11


In [25]:
my_name="Seher Sümeyye Tosun"
for letter in(my_name):
    print(letter)

S
e
h
e
r
 
S
ü
m
e
y
y
e
 
T
o
s
u
n


In [41]:
arr=[1,4,6,8,2,7,3,7]
length=len(arr)
sum = 0
i = 0
while i < length:
    sum = sum + arr[i]
    i = i+1
print("Sum", sum)

8
Sum 38


In [48]:
def sum_function(a,b):
    summation = a + b
    print(summation)
x = 10
y = 24
sum_function(x,y)
sum_function(50,74)

34
124
